default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sns_rails_development

test:
  <<: *default
  database: sns_rails_test

production:
 <<: *default
 database: sns_rails_production
 username: sns_rails
 password: <%= ENV['DATABASE_PASSWORD'] %>
 host: <%= ENV['DATABASE_HOST'] %>
